---
# Need to run 'ansible-galaxy collection install ansible.posix' before using
- hosts: all
  become: true
  tasks:
  - name: Stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: false

  - name: Set SELinux in permissive mode, logging actions that would be blocked
    ansible.posix.selinux:
      policy: targeted
      state: permissive

  - name: Disable swap for the currently running instance
    shell: |
      swapoff -a

  - name: Ensure swap is disabled on reboot
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$' # Matches any line that contains swap sw, if it's not already commented
      replace: '# \1'

  - name: Add Docker yum repo
    shell: |
      yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Add Kubernetes yum repo
    yum_repository:
      name: kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled: 1
      gpgcheck: 1
      gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude: kubelet kubeadm kubectl
      description: Kubernetes repo

  - name: Install packages
    yum:
      name:
      - containerd
      - kubelet
      - kubeadm
      - kubectl
      - nfs-utils
      disable_excludes: all
      exclude: kubernetes
      state: present

  - name: Configure containerd networking
    blockinfile:
      create: true
      path: /etc/modules-load.d/containerd.conf
      block: |
        overlay
        br_netfilter

  - name: Enable kernel modules
    shell: |
      modprobe overlay
      modprobe br_netfilter

  - name: Configure IP forwarding and iptables
    blockinfile:
      create: true
      path: /etc/sysctl.conf
      block: |
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1

  - name: Persist changes
    command: sysctl -p

  - name: Get node IP addr
    shell: ip a l eth1 | awk '/inet / { print $2 }' | awk -F '/' '{ print $1 }'
    register: ip

  - name: Print ip
    debug:
      var: ip
      verbosity: 2

  - name: Add node IP addr to kubelet
    replace:
      path: /etc/sysconfig/kubelet
      regexp: '^KUBELET_EXTRA_ARGS='
      replace: 'KUBELET_EXTRA_ARGS=--node-ip={{ ip.stdout }}'

  - name: Remove containerd config.toml
    file:
      path: /etc/containerd/config.toml
      state: absent

  - name: Start service containerd
    systemd:
      name: containerd
      state: restarted
      enabled: true

  - name: Copy the join command to server location
    copy:
      src: join
      dest: /tmp/join.sh
      mode: '0777'

  - name: Join the node to cluster
    command: sh /tmp/join.sh

  - name: Delete join script
    file:
      path: /tmp/joing.sh
      state: absent

  - name: Insert cluster's servers in /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.56.9  nfs-server.chmurki.kti.pl nfs-server
        192.168.56.10 controlplane.chmurki.kti.pl controlplane
        192.168.56.11 node-1.chmurki.kti.pl node-1
        192.168.56.12 node-2.chmurki.kti.pl node-2
