apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-express
  name: mongo-express
  namespace: chmurki
spec:
  replicas: 1
  selector:
    matchLabels:
      role: express
  template:
    metadata:
      labels:
        role: express
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://my-user:mamut123@mongodb-svc:27017/
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_ADMINUSERNAME
              value: "my-user"
            - name: ME_CONFIG_ADMINPASSWORD
              value: "mamut123"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
  labels:
    name: mongo-express
  namespace: chmurki
spec:
  type: NodePort
  selector:
    role: express
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
