#! vagrant

BOX = "generic/centos7"
N = 2

Vagrant.configure("2") do |config|

  #nfs server
  config.vm.define "nfs-server" do |ns|
      ns.vm.box = BOX
      ns.vm.network "private_network", ip: "192.168.56.9"
      ns.vm.hostname = "nfs-server"
      ns.ssh.insert_key = false
      ns.ssh.forward_agent = true
      ns.vm.provider "virtualbox" do |vb|
          vb.memory = 1024
          vb.cpus = 1
          vb.name = "nfs-server"
      end
     ns.vm.provision "ansible" do |ansible|
       ansible.playbook="playbooks/nfs-server.yml"
     end
  end

  #k8s controlplane
  config.vm.define "controlplane" do |cp|
      cp.vm.box = BOX
      cp.vm.network "private_network", ip: "192.168.56.10"
      cp.vm.hostname = "controlplane"
      cp.ssh.insert_key = false
      cp.ssh.forward_agent = true
      cp.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 2
          vb.name = "controlplane"
      end
     cp.vm.provision "ansible" do |ansible|
       ansible.playbook="playbooks/controlplane.yml"
     end
  end

  #k8s nodes
  (1..N).each do |i|
    config.vm.define "node-#{i}" do |node|
        node.vm.box = BOX
        node.vm.network "private_network", ip: "192.168.56.#{i + 10}"
        node.vm.hostname = "node-#{i}"
        node.ssh.insert_key = false
        node.ssh.forward_agent = true
        node.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
            vb.name = "node-#{i}"
        end
        node.vm.provision "ansible" do |ansible|
          ansible.playbook="playbooks/node.yml"
        end
    end
  end
end
