apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-storage
  namespace: chmurki
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: "/srv/nfs/kubedata/storage"
    server: 192.168.56.9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-shared-pvc
  namespace: chmurki
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: database-storage
