---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM-SHA-1"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: root
          db: admin
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      serviceName:
        spec:
          type: NodePort
          ports:
            - port: 27017
              targetPort: 27017
              nodePort: 30017 # Node port
              protocol: TCP
      template:
        spec:
          terminationGracePeriodSeconds: 30
          containers:
            - name: "mongodb-agent"
              resources:
                requests:
                  cpu: 200m
                  memory: 200M
                limits:
                  cpu: 400m
                  memory: 600M
            - name: "mongod"
              resources:
                requests:
                  cpu: 300m
                  memory: 400M
                limits:
                  cpu: 400m
                  memory: 600M
      volumeClaimTemplates:
        - metadata:
            name: data-volume
            volume.beta.kubernetes.io/storage-class: "nfs-client"
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "nfs-client"
            resources:
              requests:
                storage: 2G
        - metadata:
            name: logs-volume
            volume.beta.kubernetes.io/storage-class: "nfs-client"
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "nfs-client"
            resources:
              requests:
                storage: 500M

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: mamut123
