apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-storage
  namespace: chmurki
  annotations:
    volume.beta.kubernetes.io/storage-class: "persistent"
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: "/srv/nfs/kubedata/storage"
    server: nfs-server.chmurki.kti.pl
